select
  chps.id_hand as hand_id,
  chps.id_player as player_id,
  
  chps.flg_f_highcard as had_highcard_flop,
  chps.flg_f_1pair as had_pair_flop,
  chps.flg_f_2pair as had_two_pair_flop,
  chps.flg_f_threeoak as had_set_flop,
  chps.flg_f_straight as had_straight_flop,
  chps.flg_f_flush as had_flush_flop,
  chps.flg_f_fullhouse as had_fullhouse_flop,
  chps.flg_f_fouroak as had_quads_flop,
  chps.flg_f_strflush as had_straight_flush_flop,
  chps.id_f_hand_strength as hand_strength_flop_id,
  chps.id_f_kicker_strength as hand_strength_kicker_flop_id,
  chps.val_f_hole_cards_used as num_hole_cards_used_flop,
  chps.flg_f_gutshot_draw as had_gutshot_draw_flop,
  chps.flg_f_straight_draw as had_open_ended_straight_draw_flop,
  chps.flg_f_2gutshot_draw as had_double_gutter_straight_draw_flop,
  chps.flg_f_flush_draw as had_flush_draw_flop,
  chps.flg_f_bflush_draw as had_backdoor_flush_draw_flop,
  chps.flg_f_bstraight_draw as had_backdoor_straight_draw_flop,
  chps.id_f_flush_draw_strength as flush_draw_strength_flop_id,
  chps.val_f_straight_draw_nut_outs as num_straight_nut_outs_flop,
  chps.val_f_straight_draw_nonnut_outs as num_straight_nonnut_outs_flop,
  chps.flg_f_nut_flush_blocker as had_nut_flush_blocker_flop,
  
  chps.flg_t_highcard as had_highcard_turn,
  chps.flg_t_1pair as had_pair_turn,
  chps.flg_t_2pair as had_two_pair_turn,
  chps.flg_t_threeoak as had_set_turn,
  chps.flg_t_straight as had_straight_turn,
  chps.flg_t_flush as had_flush_turn,
  chps.flg_t_fullhouse as had_fullhouse_turn,
  chps.flg_t_fouroak as had_quads_turn,
  chps.flg_t_strflush as had_straight_flush_turn,
  chps.id_t_hand_strength as hand_strength_turn_id,
  chps.id_t_kicker_strength as hand_strength_kicker_turn_id,
  chps.val_t_hole_cards_used as num_hole_cards_used_turn,
  chps.flg_t_gutshot_draw as had_gutshot_draw_turn,
  chps.flg_t_straight_draw as had_open_ended_straight_draw_turn,
  chps.flg_t_2gutshot_draw as had_double_gutter_straight_draw_turn,
  chps.flg_t_flush_draw as had_flush_draw_turn,
  chps.id_t_flush_draw_strength as flush_draw_strength_turn_id,
  chps.val_t_straight_draw_nut_outs as num_straight_nut_outs_turn,
  chps.val_t_straight_draw_nonnut_outs as num_straight_nonnut_outs_turn,
  chps.flg_t_nut_flush_blocker as had_nut_flush_blocker_turn,
  
  chps.flg_r_highcard as had_highcard_river,
  chps.flg_r_1pair as had_pair_river,
  chps.flg_r_2pair as had_two_pair_river,
  chps.flg_r_threeoak as had_set_river,
  chps.flg_r_straight as had_straight_river,
  chps.flg_r_flush as had_flush_river,
  chps.flg_r_fullhouse as had_fullhouse_river,
  chps.flg_r_fouroak as had_quads_river,
  chps.flg_r_strflush as had_straight_flush_river,
  chps.id_r_hand_strength as hand_strength_river_id,
  chps.id_r_kicker_strength as hand_strength_kicker_river_id,
  chps.val_r_hole_cards_used as num_hole_cards_used_river,
  chps.flg_r_nut_flush_blocker as had_nut_flush_blocker_river,
  
  psp.player_name
from {{ source("pt4", "cash_hand_player_combinations") }} as chps
inner join {{ ref("pokerstars_players") }} as psp
  on chps.id_player = psp.player_id
